### ISSUE TITLE
helm 3 package is stripping comments from values.yaml

### ISSUE THREAD

**Issue by SrikanthSrinivasamurthy** [kokuwaio/helm-maven-plugin#90] opened 2020-07-28 16:06 UTC
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG REPORT

**Environment (plugin version, maven version, OS, ...)**:  helm-maven-plugin:5.5 , Apache Maven 3.5.2 , windows 

**What happened**: helm:package goal removing all commented lines in values.yaml

**What you expected to happen**: commented lines and format should be present

**How to reproduce it** (as minimally and precisely as possible):  execute package goal

**Anything else we need to know**: check this for more info https://github.com/helm/helm/issues/8526 
if you run `helm packge mychart\` and check the values.yaml in tgz its fine. run helm-maven-plugin with package goal in that new tgz its removed commented lines from values.yaml
[mvnOutput.txt](https://github.com/kiwigrid/helm-maven-plugin/files/4989568/mvnOutput.txt)

[values.txt](https://github.com/kiwigrid/helm-maven-plugin/files/4989573/values.txt)

**Comment by mederel** [comment] 2020-10-14 12:33
Hi @SrikanthSrinivasamurthy  I don't think it is the plugin that is at fault here. Indeed if you look the source code here, it is merely call a helm command: https://github.com/kiwigrid/helm-maven-plugin/blob/master/src/main/java/com/kiwigrid/helm/maven/plugin/PackageMojo.java

I think however that it is the fact that a version or apiVersion is defined in the configuration makes the plugin add the --version or --app-version the helm command. I think that in this case helm does a parsing of your values.yaml to inject the versions before writing the file. I think it is at that time that the comments are lost.

**Comment by sschnabe** [comment] 2022-08-24 07:59
Cannot reproduce with the invoker tests. Closing this ticket.

**Closed by sschnabe** 2022-08-24 07:59 UTC
